### ISSUE TITLE
CircleCI: Pipeline fails with "report" job

### ISSUE THREAD

**Issue by amotl** [panodata/grafana-map-panel#14]
Dear @ryantxu,

the CI pipeline for the "with-toolkit" branch currently seems to fail - croaking with `Error: Unable to read: grafana-experiments`, see [1]. Is there anything you might be able to do about it?

With kind regards,
Andreas.

[1] https://circleci.com/gh/panodata/grafana-worldmap-panel/55#config/containers/0

**Comment by ryantxu** [comment]
This is an issue with aws credentials -- I added them on the other repository, but not for `panodata`  I need a better way for non-grafana repos to support this, but have not done it yet :)

Ideally it would post the report.json to grafan.com

**Comment by amotl** [comment]
Dear Ryan,

thanks for letting me know. Is it possible to re-add the aws credentials for that just for the time being in order to heal the CI pipeline or shall we just get rid of the reporting feature in the meanwhile?

With kind regards,
Andreas.

**Comment by ryantxu** [comment]
I just added the aws credentials... hopefully that fixes it

**Comment by ryantxu** [comment]
![image](https://user-images.githubusercontent.com/705951/65913500-e6454b80-e384-11e9-8d41-0af8ff27483a.png)

**Comment by amotl** [comment]
> I just added the aws credentials... hopefully that fixes it

Thanks a bunch!

**Comment by amotl** [comment]
Dear @ryantxu,

we just added CircleCI-testing against Grafana 6.4.4 and updated `yarn.lock`, which slipped through. While all tests passed successfully, the "report" job is failing again. Might the renaming (#21) be the reason for that?

So, may I humbly ask you to have a look / quickly fix things again in order to heal that CircleCI pipeline?

Thanks already and with kind regards,
Andreas.

[1] https://circleci.com/gh/panodata/grafana-map-panel/122

**Comment by ryantxu** [comment]
yes -- issue caused by the restructuring of the zip file.

We are going to branch 6.5-beta tomorrow, and I will then focus on making sure toolkit builds everythign properly and sends it through CI without issue before 6.5-beta2 (likely a week later)

**Comment by amotl** [comment]
Dear Ryan,

> issue caused by the restructuring of the zip file.

I see. Thanks for letting me know. Is there anything we can do about it? Or _did_ you do so already?

> We are going to branch 6.5-beta tomorrow, and I will **then** focus on [...]

Ah i see. Good luck with 6.5 then!

Cheers,
Andreas.

**Comment by amotl** [comment]
Dear @ryantxu,

may I humbly ask you to have a look why the "report" job on CircleCI might be failing due to restructuring of the zip file?

Thanks already and with kind regards,
Andreas.

**Comment by ryantxu** [comment]
Check:
https://github.com/panodata/grafana-map-panel/pull/36

**Comment by amotl** [comment]
Thanks a bunch, @ryantxu!
