### ISSUE TITLE
Error in coordinates mode: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by amfgomez** [panodata/grafana-map-panel#47]
Hello
I am testing your plugin maps and when I have set location source field like "obtain label from database" and "Geopoint format" like coordinates. 

The plugin returns the following error:

![image](https://user-images.githubusercontent.com/42830128/72915109-12277b00-3d40-11ea-96f4-3e283d347cf0.png)

Thanks in advance.

**Comment by amfgomez** [comment]
I have found the trouble,

Grafana can not load two different plugin maps at the same time.

**Comment by amotl** [comment]
@wetterfrosch has been observing the same thing recently. While it should work in theory, something happens under the hood which makes this thing croak.

However, we have been able to confirm that multiple instances of our fork actually work within the same dashboard.

**Comment by amfgomez** [comment]
@amotl in my case, I have implemented 2 grafana-map and 1 worldmap-panel. 
I have observed that if grafana-map works, worldmap-panel wont work. and vice versa.

I believe that It is a grafana problem.

**Comment by amotl** [comment]
Right. We investigated the very same scenario just yesterday. After switching every map to `grafana-map-panel`, things started working flawlessly.

**Comment by amfgomez** [comment]
I am going to test this option.

I am making the changes in grafana-map from custom-panel.  As soon as I will try it. I will write about my experience. Although I will find the same trouble because I need a simple world map and another with 2 layers more.

Thank you very much.

**Comment by amotl** [comment]
> Although I will find the same trouble because I need a simple world map and another with 2 layers more.

Do you mean you want to display multiple metrics on the same map like outlined within #43?

**Comment by amfgomez** [comment]
I need a world map with the town border in red and another without this.

I think that two different plugin will be necesary.  or not?

**Comment by amotl** [comment]
> I need a world map with the town border in red and another without this.

I see. So you are looking at real WMS Layers for Leaflet here? In this case, #29 and/or #40 might be closer to what you are asking for?

> I think that two different plugin will be necessary, no?

If you want to display two maps, sure you will have to have two instances of Map Panel. Please correct me if you believe I am getting you wrong here.

**Comment by amotl** [comment]
Let's close this issue and continue that discussion within #48. Feel free to reopen if the core of this issue hasn't been solved for you.

**Comment by DmitrySidorow** [comment]
same issue. https://github.com/pR0Ps/grafana-trackmap-panel/issues/43
any solutions?

**Comment by amotl** [comment]
Dear Dmitry,

thanks for writing in. I've just replied to your question at https://github.com/pR0Ps/grafana-trackmap-panel/issues/43#issuecomment-722296549.

With kind regards,
Andreas.
