### ISSUE TITLE
Building 0.9.0 fails

### ISSUE THREAD

**Issue by amotl** [panodata/grafana-map-panel#56]
@vmanju123 reported within https://github.com/grafana/worldmap-panel/pull/129:

> I tried downloading the latest DEV branch code 0.9.0 and compile it. I am on the Grafana 6.5.2 code base and observe the following error while compiling:

```
ERROR in /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/src/core.ts
[tsl] ERROR in /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/src/core.ts(54,17)
TS2339: Property 'url' does not exist on type 'JQueryXHR'.

ERROR in /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/src/core.ts
[tsl] ERROR in /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/src/core.ts(69,17)
TS2339: Property 'url' does not exist on type 'JQueryXHR'.

ERROR in /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/src/core.ts
[tsl] ERROR in /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/src/core.ts(88,17)
TS2339: Property 'url' does not exist on type 'JQueryXHR'.

ERROR in /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/src/chrome.ts
[tsl] ERROR in /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/src/chrome.ts(65,5)
TS2571: Object is of type 'unknown'.

ERROR in /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/src/chrome.ts
[tsl] ERROR in /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/src/chrome.ts(69,5)
TS2571: Object is of type 'unknown'.
Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/postcss-loader/src/index.js??ref--6-2!styles/dark.css:
Entrypoint mini-css-extract-plugin = *
[0] ../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/postcss-loader/src??ref--6-2!./styles/dark.css 1.02 KiB {0} [built]
[1] ../node_modules/css-loader/dist/runtime/api.js 2.04 KiB {0} [built]
Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/postcss-loader/src/index.js??ref--6-2!styles/light.css:
Entrypoint mini-css-extract-plugin = *
[0] ../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/postcss-loader/src??ref--6-2!./styles/light.css 778 bytes {0} [built]
[1] ../node_modules/css-loader/dist/runtime/api.js 2.04 KiB {0} [built]

Trace: Build failed
at /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/node_modules/@grafana/src/cli/utils/useSpinner.ts:13:15
at step (/root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/node_modules/tslib/tslib.js:136:27)
at Object.throw (/root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/node_modules/tslib/tslib.js:117:57)
at rejected (/root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/node_modules/tslib/tslib.js:108:69)
at
✖ Build failed
```

**Comment by amotl** [comment]
Dear @vmanju123,

thanks for writing in. I have run these commands using Yarn 1.19.1 on a fresh clone of the repository:
```
npx yarn install
npx yarn dev
```

and it builds successfully yielding a populated `dist/` folder.

With kind regards,
Andreas.

**Comment by amotl** [comment]
> I am on the Grafana 6.5.2 code base [...]

> ```
> ERROR in /root/go/src/github.com/grafana/grafana/data/plugins/grafana-map-panel/src/core.ts
> ```

Now I am getting it. It looks like you cloned the repository into the `plugins/` folder of the Grafana source tree and then tried to build the whole thing in order to embed the plugin into a custom distribution of Grafana?

I haven't done that yet, so I am sorry I can't support you on that. However, I would be interested how it will be made work.

Nevertheless, two ways of installing the plugin should definitively work.

1. Install the bundled package.
   ```
   grafana-cli \
     --pluginUrl https://packages.hiveeyes.org/grafana/grafana-map-panel/grafana-map-panel-0.9.0.zip \
     plugins install grafana-map-panel
   ```

2. Install from repository.

   2.1 Build the project
      ```
      npx yarn install
      npx yarn dev
      npx yarn watch   # optional
      ```
   2.2 Link `dist/` folder into Grafana's `plugin/` directory.
      ```
      cd /path/to/grafana/plugins
      ln -s /path/to/grafana-map-panel/dist grafana-map-panel
      ```

With kind regards,
Andreas.

**Comment by vmanju123** [comment]
I am on ubuntu 18.04, i was building using npm run build and then run grunt, did you mean npm whne you said npx above, thanks for help

**Comment by vmanju123** [comment]
I need the source to merge some custom modifications which i did in previous version, hence not installing the plugin directly

**Comment by vmanju123** [comment]
tried running yarn install, yarn dev - on running yarn dev, I get same error while compiling

**Comment by amotl** [comment]
> On running `yarn dev`, I get same error while compiling.

Seriously? Did you do it on a fresh clone of the repository? Which version of Yarn are you running?

**Comment by vmanju123** [comment]
yes i backed up old worldmap panel folder moved in new dev 0.9.0 code, named folder grafana-map-panel and tried to build it inside , i have yarn 1.12.1 version

**Comment by vmanju123** [comment]
sorry for typo, I have yarn 1.21.1 version

**Comment by amotl** [comment]
Just to make sure we are on the same page here. Without moving any code around, does this work for you?
```
git clone https://github.com/panodata/grafana-map-panel
cd grafana-map-panel
yarn install
yarn build
```

**Comment by vmanju123** [comment]
yes correct, upon yarn build, i see the error

**Comment by amotl** [comment]
Does https://github.com/cypress-io/cypress/issues/2363#issuecomment-440998682 eventually fix your issue?

**Comment by amotl** [comment]
For the sake of completeness, these are the versions of components I am using:
```
$ node --version
v12.12.0

$ yarn --version
1.19.1

$ npx tsc --version
Version 3.6.3
```

**Comment by amotl** [comment]
Have you been able to resolve the issues you have been observing?

**Comment by vmanju123** [comment]
no, i moved to binary version for now, don't know how to resolve the source code build issue

**Comment by amotl** [comment]
Hmm, bummer!

> I am on Ubuntu 18.04 [...]

I will spin up a VM and check the build process there.

**Comment by vmanju123** [comment]
ok, thanks

**Comment by amotl** [comment]
Dear @vmanju123,

I have tried the building on Ubuntu 18 like outlined here:
```
# Enter VM.
vagrant ssh daqzilla-ubuntu18

# Install packages.
sudo su --command 'apt-get install git nodejs npm; npm install -g yarn'

# Check versions.
cat /etc/os-release | grep PRETTY
PRETTY_NAME="Ubuntu 18.04.4 LTS"

node --version
v8.10.0

yarn --version
1.22.4

# Acquire sources.
mkdir -p develop; cd !$
git clone https://github.com/panodata/grafana-map-panel
cd grafana-map-panel

# Install dependencies.
yarn install

# Build plugin.
yarn build
```

It also worked perfectly on my end:
```
yarn run v1.22.4
$ grafana-toolkit plugin:build
✔ Cleaning
✔ Preparing
✔ Prettier check
✔ Linting
✔ Compiling...
Done in 38.12s.
```

I had encountered two minor hiccups:
- `yarn install` had to be invoked twice to pick up `grafana-toolkit`.
- `Error: spawn ENOMEM` was mitigated by assigning the machine more memory (2G).

Now, I am running out of ideas what might be happening on your machine.

With kind regards,
Andreas.

**Comment by amotl** [comment]
> Now, I am running out of ideas what might be happening on your end.

Do you have any global `tsconfig.json` or `tslint.json` files installed on your machine or within your user profile which might eventually override any settings from the files included within the repository?

**Comment by vmanju123** [comment]
I moved on to binary 0.9.0 package in our production and it has most of components what i need, if i have to re-simulate this i have to test it on our DEV environment, which i will in next couple of weeks

thanks for your attention though,if its specific to my environment, you may close the issue for now

**Comment by amotl** [comment]
Dear @vmanju123,

thanks. I am happy to keep it open until we have resolved this issue. Do you have any ideas about why it wouldn't work in your environment?

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @vmanju123,

we recently upgraded the development rig and building should work based on the guidelines in [CONTRIBUTING.md](https://github.com/panodata/grafana-map-panel/blob/develop/CONTRIBUTING.md). Let me know if you experience any problems with that.

With kind regards,
Andreas.
