### ISSUE TITLE
Clickthrough URLs with $__field_ variables don't work with Elasticsearch data source

### ISSUE THREAD

**Issue by amotl** [panodata/grafana-map-panel#57]
@vmanju123 reported at https://github.com/grafana/worldmap-panel/issues/257:

> I am using 0.9.0 map panel with Grafana 6.5.2.
>
> I am trying to pass the URL as below
```
https://xyz.com/d/xyz-monitor/xyz-monitor?&from=${__from}&to=${__to}&var-Filter=clientGeo|=|${__field_clientGeo}&var-Filter=applicationDescription|=|${__field_applicationDescription}
```

> In the above URL, `clientGeo` is the geo hashpoint and `applicationDescription` is another field. Both fields coming from elastic search query.
>
> I can see `__from` and `__to` built in variables picking up the time fields form the main panel but `clientGeo` and `applicationDescription` are not resolving to values. Both `clientGeo` and `applicationDescription` fields are in the elastic query and returning data to main panel as I can see data on map panel, but not getting resolved to values in the click through URL.
>
> Looking at he clickthrough URL information I saw that we need to prefix with `$__field_` with each data field in URL, but it does not seem to be working or I am doing something wrong. Any help is appreciated.
>
> thanks

**Comment by amotl** [comment]
@vmanju123 added a remark:
> The same issue is being discussed within #12.

**Comment by amotl** [comment]
Dear @vmanju123,

apparently, this is only implemented within `setTableValues`, so it will probably only work when using data in table format.

https://github.com/panodata/grafana-map-panel/blob/0.9.0/src/data_formatter.ts#L352-L357

Am I correct to assume data from Elasticsearch is **not** using table format?

With kind regards,
Andreas.

**Comment by vmanju123** [comment]
I can confirm now that it is indeed working for Table format, since i have time series data in es database

**Comment by amotl** [comment]
78882ec1 adds a test for checking "clickthroughUrl" interpolation when using table format.

**Comment by amotl** [comment]
> I can confirm now that it is indeed working for Table format, since i have time series data in es database.

Does this mean you have been able to make it work by switching to "table format" while still using the same Elasticsearch data source as before?

**Comment by amotl** [comment]
Dear @vmanju123,

I haven't used the Elasticsearch location data source - as of "**geohash**: An ElasticSearch query that returns geohashes" - yet. Now, c800ca3b improves the test suite by adding tests for checking the corresponding code path through [`setGeohashValues()`](https://github.com/panodata/grafana-map-panel/blob/0.9.0/src/data_formatter.ts#L165-L252).

On top of that, 99f1810b adds the `__field_` interpolation feature, now also for the Elasticsearch data source.

Would that [also] improve your situation? As we are not using Grafana with Elasticsearch, I can't tell if this makes any sense and will be happy about any feedback from you. Please let me know when I should build a new release which includes these changes.

With kind regards,
Andreas.

cc @rsaifulin, @weedaj, @krzysion

**Comment by vmanju123** [comment]
as i mentioned i am using the __field_ variables in URL and its working fine for my elastic queries

**Comment by robouden** [comment]
vamnju123

You have online dash board with example. We at Safecast tried to use the $__field variables but that did not work. See attached screenshots.
![Screenshot from 2020-07-20 10-37-07](https://user-images.githubusercontent.com/1387190/88380782-29731e00-cde0-11ea-8a73-f6dcf17e9ea2.png)

![Screenshot from 2020-07-20 10-37-25](https://user-images.githubusercontent.com/1387190/88380905-60493400-cde0-11ea-97d9-42b046009993.png)
![Uploading Screenshot from 2020-07-20 10-39-28.png…]()

**Comment by weedaj** [comment]
hi, I'm still struggling. Could you give me an explicit example in below
situation?

I'm running an Elastic query:

[image: image.png]

The map populates fine. I need the bcc.sc.location.keyword (set as 'Label
field') value set as var-location in the clickthrough URL:
 /v7/d/MYDASHBOARD/&var-location=XXX
With that given, what would I need to populate in respectively 'Link field'
and 'Clickthrough URL'?

Thanks in advance for your help.

Jeroen


Op wo 24 jun. 2020 om 18:07 schreef vmanju123 <notifications@github.com>:

**Comment by robouden** [comment]
Any updates on the issue?

**Comment by robouden** [comment]
Any updates on the issue?

**Comment by amotl** [comment]
Dear Rob,

I believe it would work with data coming from InfluxDB in table format as outlined within https://github.com/panodata/grafana-map-panel/issues/57#issuecomment-598802025 already. We are using InfluxDB, so this was obvious to have at the first place.

Apart from that, I've added support for data coming from Elasticsearch the other day, see https://github.com/panodata/grafana-map-panel/issues/57#issuecomment-599838746.

Apparently, @vmanju123 confirmed it worked for them. However, I only see now that @matschaffer replied at https://github.com/panodata/grafana-map-panel/commit/99f1810b0f10fd4407d81fe17d8e76df530069c5#commitcomment-40707078 and that he might also be struggling. Sorry to hear that.

Maybe you can share more details from the edit screen of your dashboard?

With kind regards,
Andreas.

**Comment by robouden** [comment]
Andreas,

Thank you for your reply.

What we try to do is open a new tab with detail information about sensors.
The links for the click-through work fine in tables, but not in the map
click-throughs. See attached screenshot how we implemented the setup.

If you need more detail information, do not hesitate to ask us.
We hope this would help you to troubleshoot the issue.

Regards,
Rob Oudendijk





Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> linkedin:robouden
<https://www.linkedin.com/in/roboudendijk>

**Comment by amotl** [comment]
Hi Rob,

> See attached screenshot how we implemented the setup.

Can not see it.

Cheers,
Andreas.

**Comment by robouden** [comment]
![Screenshot from 2020-10-22 11-27-50](https://user-images.githubusercontent.com/1387190/96843549-6a370d80-1489-11eb-953c-e65d7f060f76.png)
![Screenshot from 2020-10-22 11-26-33](https://user-images.githubusercontent.com/1387190/96843577-70c58500-1489-11eb-8ade-315607cb9295.png)
![Screenshot from 2020-10-22 11-27-01](https://user-images.githubusercontent.com/1387190/96843584-74f1a280-1489-11eb-9530-c8ed4e1cf03a.png)
![Screenshot from 2020-10-22 11-25-35](https://user-images.githubusercontent.com/1387190/96843589-76bb6600-1489-11eb-8cb4-4d822aad217a.png)

**Comment by robouden** [comment]
Andreas,

Sorry. I replied in an email with attachments. Seems that did not wok for GitHub.
Uploaded them here just before.

Regards,
rob

**Comment by amotl** [comment]
Thanks Rob. Is `$device_urn` coming from a Grafana Variable or from the database? If it is coming from the database, you probably should use `$__field_device_urn` there within the `Clickthrough URL`.

**Comment by robouden** [comment]
Andreas,

We tried both with and without. Same results. 
Any other idea how to fix it?

regards,
rob

**Comment by robouden** [comment]
Andreas,

If we click on the hovering point the page opens with the following URL: [](https://grafana.safecast.cc/d/DFSxrOLWk/safecast-device-details?orgId=1&from=now-2d&to=now&var-device_urn=$__field_device_urn) instead of supplying the data from the requested field. On the table is works fine.

regards,
rob

**Comment by amotl** [comment]
Sorry. Maybe this is coming from the specific style of data source you are using here. There are many intertwingulating things within the code base...

![image](https://user-images.githubusercontent.com/453543/96848428-b7e55300-1454-11eb-99c7-9026476f0d27.png)

**Comment by amotl** [comment]
Hi Rob,

I just reviewed the changelog [1] and found
- _Interpolate datapoint field values with __field_ prefix into transformation data, now also for elasticsearch queries._

not to be part of a release yet. Are you running a custom build or did you just install 0.9.0? If so, that might be the root cause!

With kind regards,
Andreas.

[1] https://github.com/panodata/grafana-map-panel/blob/develop/CHANGELOG.md

**Comment by robouden** [comment]
Andreas,

We are running 0.9.0 as far as I know. I will check to be sure. 
Sorry for my innocent, but how to run a custom build?

regards
Rob Oudendijk

**Comment by robouden** [comment]
OOPs. maybe not true.

We are running a script :/usr/sbin/grafana-cli --pluginUrl https://github.com/panodata/grafana-map-panel/archive/4f4765b68b2c02ca7de2b36dcc24349b5e10ef47.zip plugins install grafana-worldmap-panel-ng

not sure what version that is.

regards,
rob

**Comment by robouden** [comment]
Andreas,

Installed the latest development code from https://github.com/panodata/grafana-map-panel/archive/develop.zip and restarted the Grafana server. Results are still the same.

Any other suggestions? 

BTW how to check what version of the plugin the browser is using?

regards,
rob

**Comment by amotl** [comment]
Dear Rob,

downloading the sources will definitively not work. You have to build/compile them. If you dare to, you might find some pointers how to do that within [1].

Sorry that I am too busy right now to deliver that for you. Please let me know how that goes for you in general. On the other hand, I will try to come back to giving some love to that repository again. There are also some great contributions from @JonasProgrammer still lingering within pull requests.

With kind regards,
Andreas.

[1] https://github.com/panodata/grafana-map-panel/blob/develop/CONTRIBUTING.md

**Comment by amotl** [comment]
> BTW how to check what version of the plugin the browser is using?

I don't know from the top of my head. Maybe that command will also display the plugin version(s)?
```
grafana-cli plugins ls
```

**Comment by robouden** [comment]
Andreas,

I did run the command and the reply:

*installed plugins:*
*dalvany-image-panel @ 2.1.1*
*grafana-googlesheets-datasource @ 1.0.0*
*grafana-image-renderer @ 2.0.0*
*grafana-worldmap-panel @ 0.3.2*
*grafana-map-panel @ 0.9.0*
*petrslavotinek-carpetplot-panel @ 0.1.1*
*simpod-json-datasource @ 0.1.7*


regards,
rob






Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> linkedin:robouden
<https://www.linkedin.com/in/roboudendijk>

**Comment by amotl** [comment]
> I did run the command

Excellent. Now we know how one would find out about that.

However, to run the most recent development build, you will have to follow the guidelines referenced at https://github.com/panodata/grafana-map-panel/issues/57#issuecomment-714437566.

Also, you might want to uninstall the original `grafana-worldmap-panel`. While I can't remember this detail exactly, it could be that they get in the way of each other (shouldn't happen, but still worth a try).

**Comment by robouden** [comment]
Andreas,

Trying to find the guidelines referenced at #57 (comment)
<https://github.com/panodata/grafana-map-panel/issues/57#issuecomment-714437566>.,
but I can not find them. You have a link?

regards
rob



Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> linkedin:robouden
<https://www.linkedin.com/in/roboudendijk>

**Comment by amotl** [comment]
> You have a link?

Downloading the sources will definitively not work. You will have to build/compile them. If you dare to, you might find some pointers how to do that within [1].

[1] https://github.com/panodata/grafana-map-panel/blob/develop/CONTRIBUTING.md

**Comment by matschaffer** [comment]
hi @amotl - thanks for the help so far. I downloaded and built 3f77d553d6 and it's the same behavior (looks like maybe some CSS is a little off and `src/data_formatter.test.ts` throws prettier warnings). Here's what it looks like.

<img width="1904" alt="Screen Shot 2020-10-23 at 14 32 50" src="https://user-images.githubusercontent.com/690/97016752-13fcc400-1588-11eb-9df3-d04763d802a2.png">

The clickthrough url is set to `/d/DFSxrOLWk/safecast-device-details?orgId=1&from=now-2d&to=now&var-device_urn=$__field_device_urn`

and if I click on a point I get http://grafana.127.0.0.1.nip.io:8000/d/DFSxrOLWk/safecast-device-details?orgId=1&from=now-2d&to=now&var-device_urn=$__field_device_urn&refresh=15m

Looks like the replacement just doesn't happen at all.

**Comment by matschaffer** [comment]
ah.... looks like I didn't have the docker set up quite right. I think that's probably 0.9.0 still

**Comment by matschaffer** [comment]
Got the build sorted and sure enough, click through works!

Any chance of getting a pre-release? I could set up a fork with a github action, but maybe good for other people to be able to use it too.

![showing-clickthrough-working-on-es](http://g.recordit.co/JTh8Zi8EHe.gif)

**Comment by matschaffer** [comment]
Actually who needs a proper pipeline? ;) I pushed a zip to https://github.com/matschaffer/worldmap-panel/releases/tag/0.10.0-pre1 and popped it up on http://grafana-dev.safecast.cc/d/u5-KaDEWk/air-data?orgId=1

**Comment by robouden** [comment]
Nice job!! . One more request. to get multiple values on the hover panel. That would be a big help for me and probably also other people.

**Comment by amotl** [comment]
Dear @robouden and @matschaffer,

the release 0.10.0 has been made, see https://github.com/panodata/grafana-map-panel/releases/tag/0.10.0.

With kind regards,
Andreas.

P.S.:
> One more request. to get multiple values on the hover panel. That would be a big help for me and probably also other people.

Let's track this within another issue?

**Comment by robouden** [comment]
Andreas,

Yes, that is the same request ad #28.

regards,
rob

**Comment by amotl** [comment]
Thanks! Closing this now.
