### ISSUE TITLE
JSON endpoint requires URL

### ISSUE THREAD

**Issue by erlfos** [panodata/grafana-map-panel#63]
I was going to test this plugin to see if we can move over from the grafana-worldmap-panel plugin, but I stumbled upon a problem, although it could just be me doing something wrong. For "Location data" in the grafana-worldmap-panel I use a JSON file stored on the Grafana server (running in Docker) with Endpoint URL /public/myfiles/sites.json, but when I try that in grafana-map-panel I get an error "Loading locations from JSON endpoint requires URL (LocationError)". Am I doing something wrong or is using a local JSON file not supported in grafana-map-panel? The data queries (InfluxDB) are identical.
grafana-map-panel:
![image](https://user-images.githubusercontent.com/45815831/82896051-917ac480-9f55-11ea-92d3-4aea97b77b90.png)
This is in grafana-worldmap-panel:
![image](https://user-images.githubusercontent.com/45815831/82896202-d6066000-9f55-11ea-8118-eb6ef01139c2.png)

**Comment by amotl** [comment]
Dear @erlfos,

maybe it will start working when you save the dashboard and reload it?

With kind regards,
Andreas.

**Comment by erlfos** [comment]
Hi @amotl 
Yes, you were right. I had to save and do a ctrl + f5, but now it works. A bit strange, but maybe it was some kind of browser issue?
Anyways, thank you for your response,  I will continue to check out your panel, it has a lot of nice features.
